### ISSUE TITLE
Electron preload fails to load after upgrading to 4.2.0

### ISSUE THREAD

**Issue by valenvb** [getsentry/sentry-electron#637]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Electron SDK Version

4.2.0

### Electron Version

19.1.9

### What platform are you using?

None

### Steps to Reproduce

After upgrading `@sentry/electron` from `4.2.1` to  `4.2.0`, nothing loads into the Electron `BrowserWindow`s (they are white rectangles).

Devtools indicates an issue loading preload scripts because it can't find the `rrweb` module required by `@sentry/replay`.

### Expected Result

Electron preloads (and Sentry) load.

### Actual Result

Renderer process console output:

```
Unable to load preload script: path/to/app/resources/app.asar/build/preload/preload.js

Error: Cannot find module './node_modules/rrweb/es/rrweb/packages/rrweb/src/entries/all.js'
Require stack:
- path/to/app/resources/app.asar/node_modules/@sentry/replay/cjs/replay.js
- path/to/app/resources/app.asar/node_modules/@sentry/replay/cjs/integration.js
- path/to/app/resources/app.asar/node_modules/@sentry/replay/cjs/index.js
- path/to/app/resources/app.asar/node_modules/@sentry/browser/cjs/index.js
- path/to/app/resources/app.asar/node_modules/@sentry/electron/renderer/index.js
- path/to/app/resources/app.asar/build/preload/preload.js
    at Module._resolveFilename (VM97 loader:940:15)
    at i._resolveFilename (VM119 renderer_init:33:1095)
    at Module._load (VM97 loader:785:27)
    at c._load (VM116 asar_bundle:5:13343)
    at i._load (VM119 renderer_init:33:356)
    at Module.require (VM97 loader:1012:19)
    at require (VM96 helpers:102:18)
    at Object.<anonymous> (VM207 replay.js:9:1)
    at Object.<anonymous> (VM207 replay.js:1064:3)
    at Module._compile (VM97 loader:1118:14)
```

**Comment by timfish** [comment]
Thank you for reporting this. It sounds related to a recent change in dependencies for the session reply features but this wasn't picked up by any of our existing integration tests. 

Do you have a simple project that reproduces the above error?

**Comment by timfish** [comment]
Also, I'm guessing you mean it breaks on upgrading to `4.3.0` rather than `4.2.0`?

**Comment by andymartinwork** [comment]
I have the same error. Upgrading from "@sentry/electron": "4.1.0" to "@sentry/electron": "4.2.0" gives this error:

Error: Cannot find module './node_modules/rrweb/es/rrweb/packages/rrweb/src/entries/all.js'

**Comment by timfish** [comment]
@andymartinwork can you provide more details to help me reproduce this? What version of `electron-builder`, what command causes the error, etc, etc.

A basic repository demonstrating the issue is most helpful!

**Comment by phillipCouto** [comment]
> @andymartinwork can you provide more details to help me reproduce this? What version of `electron-builder`, what command causes the error, etc, etc.
> 
> A basic repository demonstrating the issue is most helpful!

This happens with electron-builder 23.6.0. When the application is packaged the rrweb package is not in the node_modules folder within the asar. Not sure but it may be related to the fact that rrweb is a dev dependency for the @sentry/replay package. I can try creating a repository to recreate the issue later if no one else does.

**Comment by timfish** [comment]
Thanks @phillipCouto. 

I just checked `/node_modules/@sentry/replay/cjs/*` after updating to the latest JavaScript SDKs and `rrweb` is now no longer referenced so this should be fixed in the next release of the Electron SDK. If everything goes to plan that will be on Monday!

**Comment by phillipCouto** [comment]
> Thanks @phillipCouto. 
> 
> I just checked `/node_modules/@sentry/replay/cjs/*` after updating to the latest JavaScript SDKs and `rrweb` is now no longer referenced so this should be fixed in the next release of the Electron SDK. If everything goes to plan that will be on Monday!

Awesome! Looking forward to testing it once it is released. For now I will keep my version at 4.1.2

**Comment by timfish** [comment]
v4.3.0 has been released. Let us know if the issue is fixed!

**Comment by valenvb** [comment]
I got pulled into other things at work after reporting this, but thanks all for jumping on this and then fix - v4.3.0 is working great for us!
