### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Christilut** [getsentry/sentry-electron#363]
## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.5.2`
- [x] Electron version - `electron@v9.4.1`
- [x] Platform - `Windows`

## Description

```
TypeError: Object(...) is not a function
    at Module.init (C:\Users\user\workspace\my-app\.webpack\main\index.js:2711:158)
    at Module../src/system/sentry.ts (C:\Users\user\workspace\my-app\.webpack\main\index.js:61734:58)
    at __webpack_require__ (C:\Users\user\workspace\my-app\.webpack\main\index.js:21:30)
    at Module../src/main.ts (C:\Users\user\workspace\my-app\.webpack\main\index.js:61297:72)
    at __webpack_require__ (C:\Users\user\workspace\my-app\.webpack\main\index.js:21:30)
    at C:\Users\user\workspace\my-app\.webpack\main\index.js:85:18
    at Object.<anonymous> (C:\Users\user\workspace\my-app\.webpack\main\index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
webpack built a902fc3ba47ce5946243 in 26053ms
```

Getting the above error after upgrading from 2.4.0 to 2.5.2.
Downgrading back to 2.4.0 works for now.

Not running the latest Electron, that might be it?

**Comment by timfish** [comment]
Nothing changed drastically between 2.4.0 and 2.5.2 and there haven't been any other reports of similar issues.

I'd be happy to look at a repository that demonstrates the issue, but without a reproducible example, I have no way to diagnose what's causing this.

**Comment by chetbox** [comment]
We are getting the same error with `@sentry/electron@v2.5.2` but not with `@sentry/electron@v2.4.0`. We are using Electron 12.0.9 with Electron Forge and `@electron-forge/plugin-webpack` 6.0.0-beta.52.

**Comment by timfish** [comment]
If someone can supply a simple reproduction of this issue I more easily advise of the cause.

**Comment by chetbox** [comment]
We don't see the issue with a fresh Electron Forge project, even after downgrading to use the same versions of `electron` (12.0.9) and `webpack` (4.44.1)

We're using Typescript and the issue persists with both `ts-loader` and `babel-loader` with `@babel/preset-typescript`.

I've tried both `const Sentry = require('@sentry/electron')` and `import * as Sentry from '@sentry/electron'` with the same results.

I'm a bit stuck as how to reproduce this in a minimal project!

**Comment by timfish** [comment]
What code does the error originate from? ie. what code does the top of the stack trace point to?

**Comment by chetbox** [comment]
Just as the stack trace above, the error occurs within the `Sentry.init`.

I tried adding logging into the `init` function but don't see the log printed. I might be barking up the wrong tree though..!

**Comment by timfish** [comment]
What does your webpack configuration look like? TypeScript config?

It seems like webpack somehow messes up the imports when bundling but nothing drastic has changed between 2.4.0 and 2.5.2.

The only time I've seen webpack bundle with no errors but it fail at something like this at runtime has been related to TypeScript `allowSyntheticDefaultImports` being enabled.

**Comment by chetbox** [comment]
We're having this problem with a project using Typescript 4.0.5.

I finally managed to repro the error in a minimal project by copying all dependencies from our project's `package.json` and `yarn.lock`: https://github.com/chetbox/sentry-electron-init-error

Thanks for looking into this, @timfish!

**Comment by chetbox** [comment]
Thanks @timfish, that works!

**Comment by chetbox** [comment]
It it possible to change the dependency on `tslib` to `>2` to ensure you end up with the right version?

**Comment by chetbox** [comment]
I've just noticed a new problem after upgrading `@sentry/electron`, `@sentry/react` and `tslib`. We use `@sentry/react` in one of our renderer processes (called `media_player`). That now seems to throw an error during initialisation and then Sentry's error handler picks it up and tries to process it resulting in an (not quite?) infinite loop.

![Screenshot from 2021-10-20 13-54-16](https://user-images.githubusercontent.com/292958/138096757-d7a7e125-f2a1-4872-8cec-5954f4a105e3.png)

Dependencies:
```json
    "@sentry/electron": "^2.5.4",
    "@sentry/react": "^6.13.3",
```

An error is logged to Sentry with the stack trace:

```
TypeError: e is not a function
  at e.add(/media_player/index.js:80:56224)
  at t._sendRequest(/media_player/index.js:80:59421)
  at t.sendEvent(/media_player/index.js:80:58847)
  at t.e.sendEvent(/media_player/index.js:80:47823)
  at t.e._sendEvent(/media_player/index.js:80:45282)
  at t._sendEvent(/media_player/index.js:80:66974)
  at ? (/media_player/index.js:80:46391)
  at Object.onfulfilled(/media_player/index.js:6:2381)
  at ? (/media_player/index.js:6:1676)
  at Array.forEach(<anonymous>)
  at e._executeHandlers(/media_player/index.js:6:1606)
  at e._attachHandler(/media_player/index.js:6:1485)
  at ? (/media_player/index.js:6:2310)
  at new e(/media_player/index.js:6:1778)
  at e.then(/media_player/index.js:6:2287)
  at t.e._processEvent(/media_player/index.js:80:46211)
  at t.e._captureEvent(/media_player/index.js:80:45350)
  at ? (/media_player/index.js:80:41273)
  at Object.onfulfilled(/media_player/index.js:6:2381)
  at ? (/media_player/index.js:6:1676)
  at Array.forEach(<anonymous>)
  at e._executeHandlers(/media_player/index.js:6:1606)
  at e._attachHandler(/media_player/index.js:6:1485)
  at ? (/media_player/index.js:6:2310)
  at new e(/media_player/index.js:6:1778)
  at e.then(/media_player/index.js:6:2287)
  at t.e.captureException(/media_player/index.js:80:41246)
  at ? (/media_player/index.js:80:46467)
  at Object.onrejected(/media_player/index.js:6:2470)
  at ? (/media_player/index.js:6:1737)
  at Array.forEach(<anonymous>)
  at e._executeHandlers(/media_player/index.js:6:1606)
  at e._attachHandler(/media_player/index.js:6:1485)
  at ? (/media_player/index.js:6:2310)
  at new e(/media_player/index.js:6:1778)
  at e.then(/media_player/index.js:6:2287)
  at t.e._processEvent(/media_player/index.js:80:46410)
  at t.e._captureEvent(/media_player/index.js:80:45350)
  at ? (/media_player/index.js:80:41273)
  at Object.onfulfilled(/media_player/index.js:6:2381)
  at ? (/media_player/index.js:6:1676)
  at Array.forEach(<anonymous>)
  at e._executeHandlers(/media_player/index.js:6:1606)
  at e._attachHandler(/media_player/index.js:6:1485)
  at ? (/media_player/index.js:6:2310)
  at new e(/media_player/index.js:6:1778)
  at e.then(/media_player/index.js:6:2287)
  at t.e.captureException(/media_player/index.js:80:41246)
  at ? (/media_player/index.js:80:46467)
  at Object.onrejected(/media_player/index.js:6:2470)
```

**Comment by timfish** [comment]
> Given that @sentry/electron has a dependency on tslib@^2.2.0 should NPM/Yarn throw an error if I have a tslib dependency of 1.x.y? If not, is it possible to express that in @sentry/electron (or webpack's) package.json?

That's not how JavaScript dependency resolution works. It's perfectly valid to have multiple versions of the same dependency in your dependency tree. 

I'm pretty sure the issue you have encountered is that you listed `tslib@1.x.y` in your dependencies and this is not compatible with your tooling. There is nothing we can do in `@sentry/electron` to ensure you've selected suitable dependencies for your webpack version.

> I've just noticed a new problem after upgrading @sentry/electron...

Please report different/unrelated issues in new Github issues rather than adding them to this discussion.

**Comment by timfish** [comment]
If anyone can reproduce this with the correct version of `tslib` installed and supply a reproduction please open a new issue!
