### ISSUE TITLE
@sentry/electron v1.2.1 build fail with Electron v7.0.0

### ISSUE THREAD

**Issue by alalamav** [getsentry/sentry-electron#218]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SKD version - `@sentry/electron@v1.2.x`
- [x] Electron version - `electron@v7.0.0`
- [x] Platform - `macos`

## Description

When I updated @sentry/electron from v0.8.1 to v1.2.1 I got the following build error:

``` sh
node_modules/@sentry/electron/dist/common.d.ts:53:32 - error TS2503: Cannot find namespace 'Electron'.
    getRendererName?(contents: Electron.WebContents): string | undefined;
```

I did not run into this issue on a separate project that also uses electron v7.0.0 in macOS. Any pointers or help would be appreciated.

**Comment by alalamav** [comment]
Relevant dependencies from `yarn.lock`:
```yaml
"@sentry/apm@5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/apm/-/apm-5.10.2.tgz#41a401b3964b68514439f8a595b12c6fd05ab21a"
  integrity sha512-rPeAFsD/6ontvs7bsuHh+XAg1ohWo04ms08SNWqEvLRQJx7WfiWnjziyC0S3dXIYZDGdhruSsqQJPJN8r6Aj5g==
  dependencies:
    "@sentry/hub" "5.10.2"
    "@sentry/minimal" "5.10.2"
    "@sentry/types" "5.10.0"
    "@sentry/utils" "5.10.2"
    tslib "^1.9.3"

"@sentry/browser@~5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/browser/-/browser-5.10.2.tgz#0bbb05505c58ea998c833cffec3f922fe4b4fa58"
  integrity sha512-r3eyBu2ln7odvWtXARCZPzpuGrKsD6U9F3gKTu4xdFkA0swSLUvS7AC2FUksj/1BE23y+eB/zzPT+RYJ58tidA==
  dependencies:
    "@sentry/core" "5.10.2"
    "@sentry/types" "5.10.0"
    "@sentry/utils" "5.10.2"
    tslib "^1.9.3"

"@sentry/core@5.10.2", "@sentry/core@~5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/core/-/core-5.10.2.tgz#1cb64489e6f8363c3249415b49d3f1289814825f"
  integrity sha512-sKVeFH3v8K8xw2vM5MKMnnyAAwih+JSE3pbNL0CcCCA+/SwX+3jeAo2BhgXev2SAR/TjWW+wmeC9TdIW7KyYbg==
  dependencies:
    "@sentry/hub" "5.10.2"
    "@sentry/minimal" "5.10.2"
    "@sentry/types" "5.10.0"
    "@sentry/utils" "5.10.2"
    tslib "^1.9.3"

"@sentry/electron@1.2.1":
  version "1.2.1"
  resolved "https://registry.yarnpkg.com/@sentry/electron/-/electron-1.2.1.tgz#edf4de4b2e680ad14aeda7ad6ef2e19f8f2015f1"
  integrity sha512-8HtBjMvLpKbGRnf/iMWd/EXYatkepf1hsY6myIjH8egyPoRNbyxJhiAFoJeZ5GLbWRCWm7UuHkG4hBeyxUNZhg==
  dependencies:
    "@sentry/browser" "~5.10.2"
    "@sentry/core" "~5.10.2"
    "@sentry/minimal" "~5.10.2"
    "@sentry/node" "~5.10.2"
    "@sentry/types" "~5.10.0"
    "@sentry/utils" "~5.10.2"
    electron-fetch "^1.4.0"
    form-data "2.5.1"
    util.promisify "1.0.0"

"@sentry/hub@5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/hub/-/hub-5.10.2.tgz#25d9f36b8f7c5cb65cf486737fa61dc9bf69b7e3"
  integrity sha512-hSlZIiu3hcR/I5yEhlpN9C0nip+U7hiRzRzUQaBiHO4YG4TC58NqnOPR89D/ekiuHIXzFpjW9OQmqtAMRoSUYA==
  dependencies:
    "@sentry/types" "5.10.0"
    "@sentry/utils" "5.10.2"
    tslib "^1.9.3"

"@sentry/minimal@5.10.2", "@sentry/minimal@~5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/minimal/-/minimal-5.10.2.tgz#267c2f3aa6877a0fe7a86971942e83f3ee616580"
  integrity sha512-GalixiM9sckYfompH5HHTp9XT2BcjawBkcl1DMEKUBEi37+kUq0bivOBmnN1G/I4/wWOUdnAI/kagDWaWpbZPg==
  dependencies:
    "@sentry/hub" "5.10.2"
    "@sentry/types" "5.10.0"
    tslib "^1.9.3"

"@sentry/node@~5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/node/-/node-5.10.2.tgz#1f5d6deefb2c1549ddb542c10952cccf5f9a4ac2"
  integrity sha512-1ib1hAhVtmfXOThpcCfR4S6wFopd6lHqgOMrAUPo9saHy8zseZPRC7iTWGoSPy2RMwjrURAk54VvFnLe7G+PdQ==
  dependencies:
    "@sentry/apm" "5.10.2"
    "@sentry/core" "5.10.2"
    "@sentry/hub" "5.10.2"
    "@sentry/types" "5.10.0"
    "@sentry/utils" "5.10.2"
    cookie "^0.3.1"
    https-proxy-agent "^3.0.0"
    lru_map "^0.3.3"
    tslib "^1.9.3"

"@sentry/types@5.10.0", "@sentry/types@~5.10.0":
  version "5.10.0"
  resolved "https://registry.yarnpkg.com/@sentry/types/-/types-5.10.0.tgz#4f0ba31b6e4d5371112c38279f11f66c73b43746"
  integrity sha512-TW20GzkCWsP6uAxR2JIpIkiitCKyIOfkyDsKBeLqYj4SaZjfvBPnzgNCcYR0L0UsP1/Es6oHooZfIGSkp6GGxQ==

"@sentry/utils@5.10.2", "@sentry/utils@~5.10.2":
  version "5.10.2"
  resolved "https://registry.yarnpkg.com/@sentry/utils/-/utils-5.10.2.tgz#261f575079d30aaf604e59f5f4de0aa21db22252"
  integrity sha512-UcbbaFpYrGSV448lQ16Cr+W/MPuKUflQQUdrMCt5vgaf5+M7kpozlcji4GGGZUCXIA7oRP93ABoXj55s1OM9zw==
  dependencies:
    "@sentry/types" "5.10.0"
    tslib "^1.9.3"
```

**Comment by timfish** [comment]
The latest version of `@sentry/electron` is 2.4.1 so I'm going to close this as stale and probably fixed but feel free open a new issue if the problem persists!
